export const cards = [
  {
    id: 1,
    alt: "penguin",
    matchingNo: 7,
    img: "./assets/penguin.png",
    visible: false,
  },
  {
    id: 2,
    alt: "ice-cream",
    matchingNo: 4,
    img: "./assets/ice-cream.png",
    visible: false,
  },
  {
    id: 3,
    alt: "musical-notes",
    matchingNo: 6,
    img: "./assets/musical-notes.png",
    visible: false,
  },
  {
    id: 4,
    alt: "crown",
    matchingNo: 3,
    img: "./assets/crown.png",
    visible: false,
  },
  {
    id: 5,
    alt: "laptop",
    matchingNo: 5,
    img: "./assets/laptop.png",
    visible: false,
  },
  {
    id: 6,
    alt: "baby-boy",
    matchingNo: 1,
    img: "./assets/baby-boy.png",
    visible: false,
  },
  {
    id: 7,
    alt: "tnt",
    matchingNo: 8,
    img: "./assets/tnt.png",
    visible: false,
  },
  {
    id: 8,
    alt: "baby-boy",
    matchingNo: 1,
    img: "./assets/baby-boy.png",
    visible: false,
  },
  {
    id: 9,
    alt: "ice-cream",
    matchingNo: 4,
    img: "./assets/ice-cream.png",
    visible: false,
  },
  {
    id: 10,
    alt: "musical-notes",
    matchingNo: 6,
    img: "./assets/musical-notes.png",
    visible: false,
  },
  {
    id: 11,
    alt: "laptop",
    matchingNo: 5,
    img: "./assets/laptop.png",
    visible: false,
  },
  {
    id: 12,
    alt: "tnt",
    matchingNo: 8,
    img: "./assets/tnt.png",
    visible: false,
  },
  {
    id: 13,
    alt: "penguin",
    matchingNo: 7,
    img: "./assets/penguin.png",
    visible: false,
  },

  {
    id: 14,
    alt: "crown",
    matchingNo: 3,
    img: "./assets/crown.png",
    visible: false,
  },
  {
    id: 15,
    alt: "frog-prince",
    matchingNo: 8,
    img: "./assets/frog-prince.png",
    visible: false,
  },
  {
    id: 16,
    alt: "frog-prince",
    matchingNo: 8,
    img: "./assets/frog-prince.png",
    visible: false,
  },
];
